global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'docker'
    static_configs:
      - targets: ['rabbitmq:15672', 'db:5432', 'web:8000']

  - job_name: 'api_clients'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'api_produits'
    static_configs:
      - targets: ['web:8001']

  - job_name: 'api_commandes'
    static_configs:
      - targets: ['web:8002']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
