name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: docker-compose build

    - name: Start services
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: |
        sleep 5
        docker ps

    - name: Run tests
      run: |
        sleep 1

    - name: Stop services
      run: docker-compose down
